config-version = 2

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    '''
    sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE;
    ~/.config/sketchybar/wm_items/aerospace_update_space_apps_all.sh;
    echo "$AEROSPACE_FOCUSED_WORKSPACE" > /tmp/aerospace_current_space;
    [[ "$AEROSPACE_FOCUSED_WORKSPACE" = 0 ]] && aerospace workspace 1;
    ''',
]

on-focus-changed = [
    'exec-and-forget ~/.config/sketchybar/wm_items/aerospace_update_current_space_apps.sh',
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ["1", "2", "3", "4", "5"]

on-mode-changed = []

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 3
outer.bottom = 28
outer.top = 3
outer.right = 3

[mode.main.binding]
ctrl-shift-h = 'focus left'
ctrl-shift-j = 'focus down'
ctrl-shift-k = 'focus up'
ctrl-shift-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

ctrl-right = 'workspace next'
ctrl-left = 'workspace prev'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-a = 'workspace 1'
alt-s = 'workspace 2'
alt-d = 'workspace 3'
alt-f = 'workspace 4'
alt-g = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

cmd-backtick = 'workspace --auto-back-and-forth 1'
cmd-esc = 'workspace-back-and-forth'

cmd-h = 'move-node-to-workspace 0'
cmd-alt-h = []                     # Disable "hide others"
cmd-m = []                         # Disable "minimize window"

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/run/current-system/sw/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']

[[on-window-detected]]
# TODO: resize the window to a specific size and position
if.app-id = 'net.kovidgoyal.kitty'
if.window-title-regex-substring = '^script kitty$'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'Google Chat'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'T3 Chat'
run = ['layout floating']
