"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
\
$fill\
$time\
\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"
vimcmd_symbol = "[<-](bold green)"
vimcmd_replace_one_symbol = "[<-](bold purple)"
vimcmd_replace_symbol = "[<-](bold purple)"
vimcmd_visual_symbol = "[<-](bold yellow)"

[hostname]
ssh_only = true
ssh_symbol = ""
style = "bold green"
format = '@[$ssh_symbol$hostname]($style) in '

[username]
style_user = "bold yellow"
format = '[$user]($style)'

[docker_context]
disabled = true

[nix_shell]
disabled = false
heuristic = true

[shell]
disabled = false
fish_indicator = ""
zsh_indicator = "% "
format = '[$indicator]($style)'

[time]
disabled = false
style = ""
time_format = "%a %b %d  %H:%M:%S"
format = '[$time]($style) '

# begin overridden sections

[directory]
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold cyan"
repo_root_format = '[$before_root_path]($style)[\[$repo_root\]]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_status]
disabled = true

[git_branch]
style = "green"
ignore_branches = ["main"]
