tick_rate = 100
default_channel = "files"
history_size = 200
global_history = false

[ui]
ui_scale = 100
orientation = "landscape"
theme = "catpuccin"

[ui.input_bar]
position = "top"
prompt = ">"
# header = "{}"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}
border_type = "rounded" # https://docs.rs/ratatui/latest/ratatui/widgets/block/enum.BorderType.html#variants

[ui.status_bar]
# separator_open = ""
# separator_close = ""
separator_open = ""
separator_close = ""
hidden = false

[ui.results_panel]
border_type = "rounded"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}

[ui.preview_panel]
size = 50
# header = ""
# footer = ""
scrollbar = true
border_type = "rounded"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}
hidden = false

[ui.help_panel]
# Whether to split the help panel by categories
show_categories = true
hidden = true

[ui.remote_control]
show_channel_descriptions = true
sort_alphabetically = true
# disabled = false

[keybindings]
esc = "quit"
ctrl-c = "quit"

# Navigation and selection
# -----------------------
down = "select_next_entry"
ctrl-n = "select_next_entry"
ctrl-j = "select_next_entry"
up = "select_prev_entry"
ctrl-p = "select_prev_entry"
ctrl-k = "select_prev_entry"

# History navigation
# -----------------
ctrl-up = "select_prev_history"
ctrl-down = "select_next_history"

# Multi-selection
# --------------
tab = "toggle_selection_down"
backtab = "toggle_selection_up"
enter = "confirm_selection"

# Preview panel control
# --------------------
pagedown = "scroll_preview_half_page_down"
pageup = "scroll_preview_half_page_up"

# Data operations
# --------------
ctrl-y = "copy_entry_to_clipboard"
ctrl-r = "reload_source"
ctrl-s = "cycle_sources"

# UI Features
# ----------
ctrl-t = "toggle_remote_control"
ctrl-o = "toggle_preview"
ctrl-h = "toggle_help"
f12 = "toggle_status_bar"
ctrl-l = "toggle_layout"

# Input field actions
# ----------------------------------------
backspace = "delete_prev_char"
ctrl-w = "delete_prev_word"
ctrl-u = "delete_line"
delete = "delete_next_char"
left = "go_to_prev_char"
right = "go_to_next_char"
home = "go_to_input_start"
ctrl-a = "go_to_input_start"
end = "go_to_input_end"
ctrl-e = "go_to_input_end"

# Event bindings
# ----------------------------------------------------------------------------
# Event bindings map non-keyboard events to actions
# This includes mouse events, resize events, and custom events
[events]
mouse-scroll-up = "scroll_preview_up"
mouse-scroll-down = "scroll_preview_down"
